vocab_list = [
    "abagment", "abyss", "acrobat", "action", "actor", "admiration", "affection", "anarchy", 
    "animal", "antelope", "anxiety", "appk", "asparaps", "attribute", "baby", "badger", 
    "banana", "bath", "beauty", "beetle", "boat", "box", "bronze", "brotherhood", "brugt", 
    "buffalo", "bullet", "butter", "butterfly", "cabbage", "cake", "campus", "candy", 
    "cannon", "canyon", "captive", "curot", "cashmere", "charm", "cherry", "child", 
    "Chile", "chisel", "church", "cider", "city", "clemency", "cloak", "club", "coat", 
    "committee", "controversy", "course", "coyote", "crater", "cracker", "daisy", "danger", 
    "day", "debate", "decay", "delerium", "demon", "depth", "devotion", "dignity", "disease", 
    "doctor", "donkey", "door", "dress", "eagle", "elephant", "emotion", "faith", "fame", 
    "farmer", "fear", "figment", "fig", "fog", "foot", "frune", "fraud", "freedom", "fruit", 
    "furnace", "garden", "gardenia", "gove", "goat", "gorilla", "government", "grasshopper", 
    "grief", "guns", "hair", "hammer", "hand", "harness", "harp", "hat", "hate", "health", 
    "height", "hill", "hunt", "hog", "hope", "horse", "hunger", "ignorance", "income", 
    "India", "infection", "jacket", "jealousy", "joy", "judgment", "juggler", "justice", 
    "king", "knee", "knife", "knuckle", "lake", "lamb", "lamp", "larceny", "lawyer", 
    "length", "lettuce", "liberty", "life", "link", "lion", "liquor", "lock", "love", 
    "loyalty", "marriage", "martyr", "maturity", "mechanic", "memory", "method", "Mexico", 
    "milk", "mind", "miner", "minister", "minute", "monkey", "moon", "moth", "motion", 
    "music", "muskrat", "nation", "need", "nurg", "nuts", "ocean", "oil", "ounce", "oven", 
    "owl", "panther", "pants", "paper", "patriot", "peace", "pen", "philosopher", "piano", 
    "picture", "pistol", "pity", "pliers", "poet", "politician", "popularity", "position", 
    "prayer", "preview", "proxy", "queen", "rabbit", "religion", "repentance", "roar", 
    "robbery", "scissors", "scout", "shame", "shape", "sheep", "silk", "skin", "sleep", 
    "sofa", "soldier", "soul", "sound", "spider", "stream", "strife", "stomach", "stool", 
    "stove", "success", "sweater", "sword", "symphony", "theory", "thirst", "thought", 
    "thumb", "time", "tin", "train", "trout", "trumpet", "truth", "tunnel", "turnip", 
    "uniform", "unit", "ukulele", "valley", "vase", "violin", "want", "warning", "wasp", 
    "water", "weight", "whiskey", "whistle", "width", "window", "wolf", "zebra", "abbess", 
    "abdication", "abdomen", "abduction", "aberration", "ability", "abode", "accordion", 
    "adage", "admiral", "advantage", "adversity", "advice", "afterlife", "agility", "agony", 
    "agreement", "air", "alcohol", "algebra", "alimony", "allegory", "alligator", "ambulance", 
    "amount", "amour", "amplifier", "anecdote", "anger", "angle", "animosity", "ankle", 
    "answer", "antitoxin", "appearance", "apple", "appliance", "aptitude", "arbiter", "arm", 
    "armadillo", "army", "array", "arrow", "artist", "assault", "athletics", "atmosphere", 
    "atrocity", "attendant", "attitude", "author", "automobile", "avalanche", "avenue", 
    "background", "bacteria", "bagpipe", "banality", "bandit", "banker", "banner", "bar", 
    "bard", "baron", "barrel", "basement", "beast", "beaver", "beggar", "belfry", "belief", 
    "belongings", "bereavement", "betrayal", "beverage", "bivouac", "blacksmith", "blandness", 
    "blasphemy", "blessing", "blister", "blood", "bloom", "blossom", "blunderbuss", "board", 
    "body", "book", "boredom", "bosom", "boss", "bottle", "boulder", "bouquet", "bowl", 
    "boy", "brain", "brassiere", "bravery", "breast", "breeze", "brutality", "brute", 
    "buffoon", "builder", "building", "bungalow", "busybody", "butcher", "cabin", 
    "camouflage", "camp", "candidate", "cane", "capacity", "car", "caravan", "cash", "cat", 
    "caterpillar", "cattle", "causality", "cell", "cellar", "centennial", "cerebrum", 
    "ceremony", "chair", "chance", "chaos", "charlatan", "charter", "chasm", "chief", "chin", 
    "chloride", "Christmas", "cigar", "circle", "circuit", "citation", "claw", "cleanness", 
    "clock", "cobblestone", "code", "coffee", "coin", "college", "colony", "combustion", 
    "comedy", "comforter", "comparison", "competence", "competition", "comrade", "comradeship", 
    "concept", "confidence", "connoisseur", "conquest", "contents", "context", "contract", 
    "contribution", "convention", "cooperation", "copybook", "cord", "core", "corn", "corner", 
    "corpse", "cost", "costume", "cottage", "cotton", "courtship", "cowhide", "cradle", 
    "crag", "cranium", "creator", "creature", "crime", "crisis", "criterion", "cuisine", 
    "custom", "daffodil", "dalliance", "damsel", "dawn", "daybreak", "daylight", "death", 
    "debacle", "deceit", "decoration", "decree", "deduction", "deed", "dell", "deluge", 
    "democracy", "destruction", "determination", "detonation", "development", "devil", 
    "diamond", "direction", "dirt", "disaster", "discipline", "disclosure", "disconnection", 
    "discovery", "discretion", "disparity", "disposition", "distinction", "distraction", 
    "disturber", "doll", "dollar", "domicile", "doorman", "dove", "drama", "dream", "dreamer", 
    "dummy", "dust", "duty", "dweller", "dynasty", "earth", "eccentricity", "economy", 
    "edifice", "edition", "effort", "ego", "elaboration", "elbow", "emancipation", 
    "embezzlement", "emergency", "emporium", "encephalon", "encore", "engagement", "engine", 
    "ensemble", "enterprise", "episode", "epistle", "equity", "errand", "evangelist", "event", 
    "evidence", "exactitude", "examination", "exclusion", "excuse", "exertion", "exhaust", 
    "exhaustion", "explanation", "expression", "extermination", "fabric", "facility", "fact", 
    "factory", "falconer", "fallacy", "fantasy", "fate", "fatigue", "fault", "feline", 
    "festivity", "feudalism", "fiord", "fire", "fireplace", "firmament", "fisherman", "flag", 
    "flesh", "flexibility", "flood", "flower", "foam", "foible", "folly", "footwear", 
    "forehead", "forest", "forethought", "fork", "form", "formation", "fortune", "fowl", 
    "fox", "franchise", "friction", "friend", "frog", "frontage", "fun", "functionary", 
    "fur", "furniture", "gadfly", "gaiety", "galaxy", "gallery", "garments", "garret", 
    "geese", "gem", "gender", "genius", "ghost", "gift", "gilt", "gingham", "girl", "gist", 
    "glacier", "glory", "glutton", "goblet", "goddess", "gold", "golf", "gore", "graduation", 
    "grandmother", "grass", "gravity", "greed", "green", "guardhouse", "gymnastics", 
    "habitation", "hairpin", "hall", "hamlet", "hankering", "happiness", "hardship", 
    "hardwood", "hatred", "headlight", "headquarters", "hearing", "heaven", "henchman", 
    "heredity", "heroism", "hide", "hierarchy", "hillside", "hindrance", "hint", "history", 
    "home", "homicide", "honeycomb", "honor", "hoof", "horsehair", "hospital", "hostage", 
    "hostility", "hotel", "hound", "hour", "house", "humor", "hurdle", "hurricane", 
    "hypothesis", "icebox", "idea", "idiom", "illusion", "immunity", "impact", "impotency", 
    "impropriety", "impulse", "inanity", "incident", "inclemency", "increment", "inducement", 
    "industry", "inebriety", "infant", "infirmary", "ingratitude", "inhabitant", "injury", 
    "ink", "inn", "insect", "insolence", "instance", "institute", "instructor", "instrument", 
    "intellect", "interest", "interim", "interview", "intimate", "investigation", "invoice", 
    "iron", "irony", "islander", "item", "jail", "jelly", "jeopardy", "joke", "journal", 
    "judge", "jury", "keg", "kerchief", "kerosene", "kettle", "kindness", "kine", "kiss", 
    "knowledge", "labyrinth", "lad", "landscape", "lark", "law", "lawn", "leaflet", "lecture", 
    "lecturer", "leggings", "legislation", "lemon", "lemonade", "leopard", "letter", 
    "letterhead", "library", "lice", "limb", "lime", "limelight", "lip", "lobster", "locker", 
    "loquacity", "lord", "lubricant", "lump", "macaroni", "machine", "madness", "magazine", 
    "magnitude", "maiden", "majority", "maker", "malady", "malaria", "malice", "mammal", 
    "management", "mantle", "market", "mast", "master", "mastery", "material", "mathematics", 
    "meadow", "meat", "medallion", "meeting", "menace", "mercy", "metal", "metropolis", 
    "microscope", "mileage", "miracle", "mirage", "mischief", "misconception", "misery", 
    "missile", "molecule", "moment", "monarch", "money", "monk", "month", "mood", "moral", 
    "morgue", "mosquito", "moss", "mother", "mountain", "mucus", "mule", "multiplication", 
    "murder", "musician", "nail", "namesake", "necessity", "nectar", "nephew", "newspaper", 
    "nightfall", "nonsense", "noose", "northwest", "nun", "nursery", "nutmeg", "nymph", 
    "oats", "obedience", "obsession", "occasion", "odor", "officer", "offshoot", "onslaught", 
    "opinion", "opium", "orchestra", "origin", "originator", "osculation", "outcome", 
    "outsider", "owner", "ownership", "oxygen", "pacifism", "pact", "painter", "palace", 
    "panic", "panorama", "party", "parity", "passageway", "passion", "patent", "peacemaker", 
    "peach", "pelt", "pencil", "pep", "pepper", "perception", "performer", "periodical", 
    "perjury", "permission", "person", "phantom", "photograph", "physician", "pianist", 
    "pipe", "piston", "plain", "plank", "plant", "pleasure", "pledge", "pole", "policeman", 
    "pollution", "portal", "portrait", "poster", "potato", "poverty", "power", "prairie", 
    "present", "pressure", "prestige", "priest", "prison", "prisoner", "procession", 
    "product", "profession", "professor", "profile", "promotion", "property", "proprietor", 
    "prosecutor", "prosperity", "pudding", "pupil", "python", "quality", "quantity", "quest", 
    "railroad", "rating", "rattle", "reaction", "recital", "recognition", "reflection", 
    "reflex", "refrigerator", "reminder", "rendezvous", "replacement", "reptile", "research", 
    "residue", "restaurant", "retailer", "revolt", "revolver", "rhapsody", "rheumatism", 
    "ritual", "river", "rock", "rod", "rosin", "rubble", "sadness", "safety", "salad", 
    "salary", "saloon", "salutation", "salute", "satire", "sauce", "savant", "scarlet", 
    "science", "scorpion", "sea", "season", "seat", "sensation", "sentiment", "serf", 
    "series", "session", "settlement", "settler", "shadow", "sheepskin", "ship", "shock", 
    "shore", "shotgun", "shriek", "sickness", "silence", "simile", "situation", "skillet", 
    "sky", "slave", "slipper", "slush", "snake", "sobriety", "socialist", "soil", "sonata", 
    "sovereign", "speakeasy", "speaker", "speech", "spire", "spirit", "spray", "spree", 
    "square", "stagecoach", "stain", "star", "steam", "steamer", "steerage", "stone", 
    "storeroom", "storm", "strawberry", "street", "strength", "string", "stub", "student", 
    "style", "substitute", "subtraction", "suds", "sugar", "sulphur", "sultan", "sunburn", 
    "sunset", "supplication", "suppression", "surtax", "swamp", "table", "tablespoon", 
    "tank", "teacher", "temerity", "tempest", "temple", "tendency", "theologian", "thicket", 
    "thief", "thistledown", "thorn", "ticket", "tidbit", "timepiece", "toast", "tobacco", 
    "tomahawk", "tomb", "tool", "tower", "toy", "traction", "tragedy", "tree", "trellis", 
    "tribute", "tripod", "troops", "trouble", "truce", "truck"]